sudo: true

language: php
php:
 - 7.0

addons:
 apt:
   packages:
   - make

before_script:
 - pecl install channel://pecl.php.net/weakref-0.3.3
 - echo | pecl install channel://pecl.php.net/yaml-2.0.2
 - git clone https://github.com/krakjoe/pthreads.git --depth=1
 - cd pthreads
 - phpize
 - ./configure
 - make
 - make install
 - cd ..
 - echo "extension=pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
 - ./ci/run.sh

notifications:
  email: false

before_deploy:
 - mv plugins/Turanic/Turanic*.phar plugins/Turanic/Turanic.phar
